apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: cG9zdGdyZXM=                     # "postgres" (base64)
  password: djhobERWMHlNQUhIbEl1cll1cGo=     # "v8hlDV0yMAHHlIurYupj" (base64)